# Generated by Django 3.2.25 on 2025-02-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_total_price_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название скидки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма скидки')),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название налога')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ставка налога')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.IntegerField(default=0, verbose_name='Сумма скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.IntegerField(default=0, verbose_name='Стоимость до скидок и налогов'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.IntegerField(default=0, verbose_name='Сумма налогов'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.discount', verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='main.Tax', verbose_name='Налоги'),
        ),
    ]
