# Generated by Django 3.2.25 on 2025-02-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20250226_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='percent',
        ),
    ]
