# Generated by Django 3.2.25 on 2025-02-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
    ]
